version: '3'

services:
  laravel-app:
    build:
      dockerfile: ./multimedia/Dockerfile
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0
    env_file: ./multimedia/.env
    volumes:
      - /var/www/laravel
      - ./multimedia:/var/www/laravel:delegated
    environment:
      APP_ENV: local
      APP_KEY: your-application-key
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: multimedia
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: multimedia
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./multimedia/mysql-scripts/multimedia.sql:/docker-entrypoint-initdb.d/multimedia.sql

volumes:
  mysql-data: